/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './app/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: 'var(--color-brand-primary)',
          light: 'var(--color-brand-primary-light)',
          dark: 'var(--color-brand-primary-dark)',
          muted: 'var(--color-brand-primary-muted)',
        },
        accent: {
          gold: 'var(--color-accent-gold)',
          'gold-light': 'var(--color-accent-gold-light)',
        },
        semantic: {
          success: 'var(--color-semantic-success)',
          warning: 'var(--color-semantic-warning)',
          error: 'var(--color-semantic-error)',
          info: 'var(--color-semantic-info)',
        },
        surface: {
          elevated: 'var(--color-surface-elevated)',
          card: 'var(--color-surface-card)',
          overlay: 'var(--color-surface-overlay)',
        },
        gray: {
          50: 'var(--color-gray-50)',
          100: 'var(--color-gray-100)',
          200: 'var(--color-gray-200)',
          300: 'var(--color-gray-300)',
          400: 'var(--color-gray-400)',
          500: 'var(--color-gray-500)',
          600: 'var(--color-gray-600)',
          700: 'var(--color-gray-700)',
          800: 'var(--color-gray-800)',
          850: 'var(--color-gray-850)',
          900: 'var(--color-gray-900)',
          950: 'var(--color-gray-950)',
        },
        bg: {
          primary: 'var(--color-bg-primary)',
          secondary: 'var(--color-bg-secondary)',
          tertiary: 'var(--color-bg-tertiary)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          tertiary: 'var(--color-text-tertiary)',
          disabled: 'var(--color-text-disabled)',
        },
        border: {
          primary: 'var(--color-border-primary)',
          secondary: 'var(--color-border-secondary)',
          focus: 'var(--color-border-focus)',
        },
      },
      fontFamily: {
        sans: ['var(--font-family-sans)'],
        mono: ['var(--font-family-mono)'],
      },
      fontSize: {
        'display-xl': ['var(--font-size-display-xl)', { lineHeight: 'var(--line-height-display-xl)', letterSpacing: 'var(--letter-spacing-display-xl)', fontWeight: 'var(--font-weight-display-xl)' }],
        'display-lg': ['var(--font-size-display-lg)', { lineHeight: 'var(--line-height-display-lg)', letterSpacing: 'var(--letter-spacing-display-lg)', fontWeight: 'var(--font-weight-display-lg)' }],
        'display-md': ['var(--font-size-display-md)', { lineHeight: 'var(--line-height-display-md)', letterSpacing: 'var(--letter-spacing-display-md)', fontWeight: 'var(--font-weight-display-md)' }],
        'heading-lg': ['var(--font-size-heading-lg)', { lineHeight: 'var(--line-height-heading-lg)', letterSpacing: 'var(--letter-spacing-heading-lg)', fontWeight: 'var(--font-weight-heading-lg)' }],
        'heading-md': ['var(--font-size-heading-md)', { lineHeight: 'var(--line-height-heading-md)', letterSpacing: 'var(--letter-spacing-heading-md)', fontWeight: 'var(--font-weight-heading-md)' }],
        'heading-sm': ['var(--font-size-heading-sm)', { lineHeight: 'var(--line-height-heading-sm)', letterSpacing: 'var(--letter-spacing-heading-sm)', fontWeight: 'var(--font-weight-heading-sm)' }],
        'body-lg': ['var(--font-size-body-lg)', { lineHeight: 'var(--line-height-body-lg)', letterSpacing: 'var(--letter-spacing-body-lg)', fontWeight: 'var(--font-weight-body-lg)' }],
        'body-md': ['var(--font-size-body-md)', { lineHeight: 'var(--line-height-body-md)', letterSpacing: 'var(--letter-spacing-body-md)', fontWeight: 'var(--font-weight-body-md)' }],
        'body-sm': ['var(--font-size-body-sm)', { lineHeight: 'var(--line-height-body-sm)', letterSpacing: 'var(--letter-spacing-body-sm)', fontWeight: 'var(--font-weight-body-sm)' }],
        'label': ['var(--font-size-label)', { lineHeight: 'var(--line-height-label)', letterSpacing: 'var(--letter-spacing-label)', fontWeight: 'var(--font-weight-label)' }],
        'caption': ['var(--font-size-caption)', { lineHeight: 'var(--line-height-caption)', letterSpacing: 'var(--letter-spacing-caption)', fontWeight: 'var(--font-weight-caption)' }],
      },
      spacing: {
        'xs': 'var(--spacing-xs)',
        'sm': 'var(--spacing-sm)',
        'md': 'var(--spacing-md)',
        'lg': 'var(--spacing-lg)',
        'xl': 'var(--spacing-xl)',
        '2xl': 'var(--spacing-2xl)',
        '3xl': 'var(--spacing-3xl)',
        '4xl': 'var(--spacing-4xl)',
        '5xl': 'var(--spacing-5xl)',
      },
      borderRadius: {
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        'full': 'var(--radius-full)',
        'button': 'var(--radius-button)',
        'card': 'var(--radius-card)',
        'input': 'var(--radius-input)',
        'chip': 'var(--radius-chip)',
      },
      transitionDuration: {
        'instant': 'var(--duration-instant)',
        'fast': 'var(--duration-fast)',
        'normal': 'var(--duration-normal)',
        'slow': 'var(--duration-slow)',
        'slower': 'var(--duration-slower)',
      },
      transitionTimingFunction: {
        'out': 'var(--ease-out)',
        'in-out': 'var(--ease-in-out)',
        'spring': 'var(--ease-spring)',
        'bounce': 'var(--ease-bounce)',
      },
      boxShadow: {
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
        'glow-brand': 'var(--shadow-glow-brand)',
      },
      zIndex: {
        'dropdown': 'var(--z-dropdown)',
        'sticky': 'var(--z-sticky)',
        'overlay': 'var(--z-overlay)',
        'modal': 'var(--z-modal)',
        'toast': 'var(--z-toast)',
        'tooltip': 'var(--z-tooltip)',
      },
    },
  },
  plugins: [],
}